### ISSUE TITLE
Transfer Known Issues from ConsenSys Best practices to SCVDB

### ISSUE THREAD

**Issue by maurelian** [maurelian/scvdb#1]
## Goal

The intention is to create an exhaustive list of anti-patterns for development of smart contracts. This is  similar to https://cwe.mitre.org/. 

## Task

As a first step towards this objective: 

1. Review the items in the [Best Practices known attacks](https://consensys.github.io/smart-contract-best-practices/known_attacks/).
2. Transpose them to the YAML format in [scvdb.yml](https://github.com/maurelian/scvdb/blob/master/scvdb.yml)

### example: 

``` 
- id: 2
    name: 'Reentrancy'
    description: 'Occurs when a contract makes a call to an external contract, which calls back into the calling contract, making an undesired state change.'
    more-info: 
      - `https://consensys.github.io/smart-contract-best-practices/known_attacks/#reentrancy`
      - `http://vessenes.com/more-ethereum-attacks-race-to-empty-is-the-real-deal/`
```
